name: argear_flutter_example
description: Demonstrates how to use the argear_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  argear_flutter:
    path: ../

  cupertino_icons: ^1.0.2
  video_player:
  flutter_hooks: ^0.17.0
  permission_handler:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
