name: argear_flutter
description: A new flutter plugin project.
version: 0.0.14
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  path_provider:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.argear_flutter
        pluginClass: ArgearFlutterPlugin
      ios:
        pluginClass: ArgearFlutterPlugin
